# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18j2D6J7dgbn4grmoYXr0bVkcpn07nrPo
"""

scores=input().split()
scores=[int(x) for x in scores]
fail_count=0
for s in scores:
 if s < 60:
    fail_count+=1
print(fail_count)
print(max(scores))
print(min(scores))

