# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11zhSxxW3J2H5a0Zx1RHljsWkChm1TrkX
"""

scores=input().split()
scores=[int(x) for x in scores]
fail_count=0
for s in scores:
 if s < 60:
    fail_count+=1
print(fail_count)


average = sum(scores) / len(scores)
print(average)